import type { Category, Service, Subcategory, Banner, Review, ProjectGalleryItem, FAQ, ServiceArea, ProviderProfession, User, ServiceRequest } from "./types";

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Construction",
    slug: "construction",
    description: "Building, renovation, and structural construction services",
    icon: "building",
    imageUrl: "https://images.pexels.com/photos/11321791/pexels-photo-11321791.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    sortOrder: 1,
    active: true,
  },
  {
    id: 2,
    name: "Electrical",
    slug: "electrical",
    description: "Wiring, installations, solar power, and electrical systems",
    icon: "zap",
    imageUrl: "https://images.pexels.com/photos/27928762/pexels-photo-27928762.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    sortOrder: 2,
    active: true,
  },
  {
    id: 3,
    name: "Plumbing",
    slug: "plumbing",
    description: "Water systems, pipe fitting, drainage, and sanitation",
    icon: "droplets",
    imageUrl: "https://images.pexels.com/photos/7859953/pexels-photo-7859953.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    sortOrder: 3,
    active: true,
  },
  {
    id: 4,
    name: "Property & Interiors",
    slug: "property",
    description: "Architectural planning, painting, roofing, and interior finishings",
    icon: "home",
    imageUrl: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    sortOrder: 4,
    active: true,
  },
];

export const mockProfessions: ProviderProfession[] = [
  { id: 1, name: "Plumber", slug: "plumber", description: "Water piping, leak repairs, bathroom fittings & drainage", icon: "🔧", sortOrder: 1, active: true },
  { id: 2, name: "Electrician", slug: "electrician", description: "Conduit wiring, fault troubleshooting, distribution boards", icon: "⚡", sortOrder: 2, active: true },
  { id: 3, name: "Painter", slug: "painter", description: "Interior & exterior wall painting, screeding & wallpaper", icon: "🎨", sortOrder: 3, active: true },
  { id: 4, name: "Carpenter", slug: "carpenter", description: "Doors, kitchen cabinets, roofing timber & woodwork", icon: "🪚", sortOrder: 4, active: true },
  { id: 5, name: "Mason", slug: "mason", description: "Bricklaying, plastering, interlocking & concrete work", icon: "🧱", sortOrder: 5, active: true },
  { id: 6, name: "Welder", slug: "welder", description: "Metal fabrication, burglary proofing, gates & tanks", icon: "🔥", sortOrder: 6, active: true },
  { id: 7, name: "Solar Engineer", slug: "solar-engineer", description: "Solar PV design, hybrid inverters & lithium batteries", icon: "☀️", sortOrder: 7, active: true },
  { id: 8, name: "HVAC / AC Technician", slug: "hvac-technician", description: "Air conditioner servicing, installation & ducting", icon: "❄️", sortOrder: 8, active: true },
  { id: 9, name: "Tiler", slug: "tiler", description: "Floor & wall ceramic, porcelain and granite tiling", icon: "🔲", sortOrder: 9, active: true },
  { id: 10, name: "Roofer", slug: "roofer", description: "Stone-coated tiles, aluminium sheets & roof truss", icon: "🏠", sortOrder: 10, active: true },
  { id: 11, name: "POP Installer", slug: "pop-installer", description: "POP ceiling designs, decorative moldings & lighting troughs", icon: "✨", sortOrder: 11, active: true },
  { id: 12, name: "Interior Designer", slug: "interior-designer", description: "Space planning, lighting design & modern fit-outs", icon: "🛋️", sortOrder: 12, active: true },
  { id: 13, name: "Civil Engineer", slug: "civil-engineer", description: "Site supervision, road design & drainage structures", icon: "📐", sortOrder: 13, active: true },
  { id: 14, name: "Structural Engineer", slug: "structural-engineer", description: "Structural drawings, calculations & load audits", icon: "🏗️", sortOrder: 14, active: true },
  { id: 15, name: "Quantity Surveyor", slug: "quantity-surveyor", description: "Bill of Quantities (BOQ), material estimation & costing", icon: "📊", sortOrder: 15, active: true },
  { id: 16, name: "Architect", slug: "architect", description: "3D architectural modeling, blueprint drawings & approvals", icon: "🏛️", sortOrder: 16, active: true },
  { id: 17, name: "Generator Technician", slug: "generator-technician", description: "Diesel & petrol generator maintenance & ATS panel wiring", icon: "⚙️", sortOrder: 17, active: true },
  { id: 18, name: "CCTV / Security Installer", slug: "cctv-installer", description: "IP camera surveillance, electric fencing & smart access", icon: "📹", sortOrder: 18, active: true },
  { id: 19, name: "Mechanical Engineer", slug: "mechanical-engineer", description: "Heavy machinery, piping networks & industrial HVAC", icon: "🛠️", sortOrder: 19, active: true },
  { id: 20, name: "Electrical Engineer", slug: "electrical-engineer", description: "High voltage transformer installation & grid setups", icon: "🔌", sortOrder: 20, active: true },
];

export const mockBanners: Banner[] = [
  {
    id: 1,
    title: "Solar Power Systems",
    subtitle: "Clean, reliable energy solutions with 5-year warranty",
    imageUrl: "https://images.pexels.com/photos/9875441/pexels-photo-9875441.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    active: true,
    sortOrder: 1,
  },
  {
    id: 2,
    title: "Building Renovation",
    subtitle: "Transform your residential or commercial space with expert engineers",
    imageUrl: "https://images.pexels.com/photos/8961438/pexels-photo-8961438.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    active: true,
    sortOrder: 2,
  },
  {
    id: 3,
    title: "Borehole & Water Systems",
    subtitle: "Complete water solution from drilling to filtration",
    imageUrl: "https://images.pexels.com/photos/7859953/pexels-photo-7859953.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    active: true,
    sortOrder: 3,
  },
];

export const mockServices: Service[] = [
  // ─── CATEGORY 1: CONSTRUCTION (4 Services - All Negotiable) ───
  {
    id: 1,
    name: "Residential Building & Structural Construction",
    slug: "residential-building",
    shortDescription: "Complete house construction from foundation laying to roof topping and finishings.",
    fullDescription: "Our residential construction service covers architectural design, structural engineering, foundation work, block work, roofing, electrical, plumbing, and interior finishings. Every project is assigned a certified site engineer.",
    categoryId: 1,
    subcategoryId: 1,
    imageUrl: "https://images.pexels.com/photos/11321791/pexels-photo-11321791.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["COREN-registered structural engineers", "Complete bill of quantities (BOQ)", "Stage-by-stage quality inspections", "Turnkey completion guarantee"]),
    estimatedPriceRange: "Custom BOQ Estimate (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 1,
  },
  {
    id: 2,
    name: "Building Renovation & Structural Remodeling",
    slug: "building-renovation-remodeling",
    shortDescription: "Comprehensive building remodelling, room extensions, structural strengthening & modern facelifts.",
    fullDescription: "Transform old properties with certified structural engineers. We handle wall removals, column reinforcements, duplex upgrades, and exterior modernizations.",
    categoryId: 1,
    subcategoryId: 2,
    imageUrl: "https://images.pexels.com/photos/8961438/pexels-photo-8961438.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Structural integrity assessment", "Modern architectural floorplan redesign", "High-grade finishing materials", "Fast project delivery schedule"]),
    estimatedPriceRange: "Custom Scope (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 2,
  },
  {
    id: 3,
    name: "Foundation Engineering, Piling & Concrete Decking",
    slug: "foundation-piling-decking",
    shortDescription: "Raft foundations, pad footings, steel reinforcement cage fabrication, and concrete floor casting.",
    fullDescription: "Heavy-duty foundation engineering engineered for swampy, solid, or rocky soil terrains. Includes soil testing, German floor casting, and vibrated suspended concrete slabs.",
    categoryId: 1,
    subcategoryId: 1,
    imageUrl: "https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Soil bearing capacity analysis", "High-yield TMT steel rebar reinforcement", "Standard ready-mix concrete C25/C30", "Laser leveling & slump testing"]),
    estimatedPriceRange: "Custom Site Estimate (Negotiable)",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 3,
  },
  {
    id: 4,
    name: "Road Interlocking, Paving & Drainage Civil Works",
    slug: "interlocking-paving-drainage",
    shortDescription: "Heavy-duty concrete paving stones, kerbs installation, perimeter drainage culverts, and compound leveling.",
    fullDescription: "Commercial and residential compound interlocking paving. Includes stone base compaction, weed-resistant sand filling, concrete kerbs, and storm-water drainage channels.",
    categoryId: 1,
    subcategoryId: 2,
    imageUrl: "https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["High-compressive 60mm & 80mm pavers", "Vibrated mechanical roller compaction", "Effective water runoff slope design", "Long-lasting erosion control"]),
    estimatedPriceRange: "Per Square Meter / Negotiable",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 4,
  },

  // ─── CATEGORY 2: ELECTRICAL (4 Services - All Negotiable) ───
  {
    id: 5,
    name: "Solar Power Systems & Hybrid Inverter Setup",
    slug: "solar-installation",
    shortDescription: "Complete solar system design, high-efficiency panel mounting, and lithium-ion battery integration.",
    fullDescription: "Transition to 24/7 reliable clean electricity. We calculate your exact energy load, design the solar array, mount premium panels, configure hybrid inverters, and integrate smart battery protection systems.",
    categoryId: 2,
    subcategoryId: 4,
    imageUrl: "https://images.pexels.com/photos/9875441/pexels-photo-9875441.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Tier-1 Mono PERC high-output panels", "Lithium (LiFePO4) battery banks", "Surge protection & lightning arresters", "5-year manufacturer warranty"]),
    estimatedPriceRange: "Custom Capacity (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 5,
  },
  {
    id: 6,
    name: "Conduit Electrical Wiring & Distribution Boards",
    slug: "electrical-wiring",
    shortDescription: "Full building electrical conduit piping, copper cabling, distribution panels & earthing systems.",
    fullDescription: "Certified industrial and residential conduit wiring. Complete distribution board (DB) installation, circuit breakers, changeover switches, and dedicated heavy-load lines for ACs and heaters.",
    categoryId: 2,
    subcategoryId: 3,
    imageUrl: "https://images.pexels.com/photos/27928762/pexels-photo-27928762.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["100% pure copper fire-retardant cables", "Schneider / Chint standard breakers", "Copper earth rod ground installation", "Phase balancing & load division"]),
    estimatedPriceRange: "Custom Building Scope (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 6,
  },
  {
    id: 7,
    name: "Electrical Fault Troubleshooting & Diagnostics",
    slug: "electrical-fault-troubleshooting",
    shortDescription: "Fast diagnostic troubleshooting for breaker trips, burning smell, short circuits & voltage drops.",
    fullDescription: "Emergency electrical fault tracing and repair. Our certified electrical engineers diagnose hidden cable faults inside walls, repair burned distribution boards, and restore safe power.",
    categoryId: 2,
    subcategoryId: 3,
    imageUrl: "https://images.pexels.com/photos/1435183/pexels-photo-1435183.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Megger insulation resistance testing", "Thermal imaging hotspot checks", "Fast 60-minute rapid dispatch", "Complete electrical safety audit"]),
    estimatedPriceRange: "Scope Based (Negotiable)",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 7,
  },
  {
    id: 8,
    name: "CCTV Surveillance, Smart Access & Electric Fencing",
    slug: "cctv-smart-security-electrical",
    shortDescription: "HD/4K security camera installation, mobile remote viewing, perimeter electric fencing & smart locks.",
    fullDescription: "Comprehensive electronic security setups for homes and corporate facilities. Includes night-vision IP cameras, network video recorders (NVR), backup battery power, and electric fence alarms.",
    categoryId: 2,
    subcategoryId: 4,
    imageUrl: "https://images.pexels.com/photos/430208/pexels-photo-430208.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["4K Ultra-HD night vision cameras", "Live mobile phone remote monitoring", "High-voltage energizer electric fencing", "Backup battery for 24/7 coverage"]),
    estimatedPriceRange: "Package Based (Negotiable)",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 8,
  },

  // ─── CATEGORY 3: PLUMBING (4 Services - All Negotiable) ───
  {
    id: 9,
    name: "PPR Water Supply Piping & Pressure Systems",
    slug: "plumbing-installation",
    shortDescription: "PPR/PEX heat-fused water supply lines, overhead tank plumbing, and automatic booster pressure pumps.",
    fullDescription: "High-grade plumbing installation for newly built residential and commercial buildings. Includes bathroom hot/cold water distribution, overhead scaffolding tank plumbing, and pressure balancing.",
    categoryId: 3,
    subcategoryId: 5,
    imageUrl: "https://images.pexels.com/photos/7859953/pexels-photo-7859953.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["PPR heat-fused leak-proof pipes", "Automatic water pressure booster pumps", "Overhead & underground tank plumbing", "Hydrostatic pressure testing"]),
    estimatedPriceRange: "Custom Scope (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 9,
  },
  {
    id: 10,
    name: "Borehole Drilling & Water Treatment Plants",
    slug: "borehole-drilling-water-treatment",
    shortDescription: "Deep industrial borehole drilling, submersible pump installation, and multi-stage water filtration plants.",
    fullDescription: "Complete potable water solutions. We conduct geophysical survey, drill deep boreholes to clean aquifers, install stainless steel submersible pumps, and setup iron removal and reverse osmosis filtration.",
    categoryId: 3,
    subcategoryId: 6,
    imageUrl: "https://images.pexels.com/photos/3825586/pexels-photo-3825586.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Geophysical electrical resistivity survey", "High-capacity submersible pumps", "Iron removal & sediment carbon filtration", "Pure laboratory-grade drinking water"]),
    estimatedPriceRange: "Custom Depth & Plant (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 10,
  },
  {
    id: 11,
    name: "Sewage Drainage, Bio-Digester & Waste Piping",
    slug: "sewage-drainage-biodigester",
    shortDescription: "Modern odorless bio-digester soakaway systems, PVC soil & waste drainage networks, and inspection chambers.",
    fullDescription: "Eliminate recurring soakaway evacuations with modern eco-friendly bio-digester systems. Includes PVC waste pipe routing, anti-odor traps, grease traps, and manhole chambers.",
    categoryId: 3,
    subcategoryId: 5,
    imageUrl: "https://images.pexels.com/photos/4792480/pexels-photo-4792480.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Modern compact bio-digester construction", "Zero odor & zero evacuation required", "Heavy-gauge PVC drain pipes", "Anti-backflow rodent prevention traps"]),
    estimatedPriceRange: "Custom Tank Size (Negotiable)",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 11,
  },
  {
    id: 12,
    name: "Luxury Sanitary Ware & Bathroom Fitting Installation",
    slug: "sanitary-ware-bathroom-fitting",
    shortDescription: "Wall-hung toilets, concealed cisterns, jacuzzi baths, glass shower cubicles, and vanity basins.",
    fullDescription: "Precision installation of designer bathroom fixtures and sanitary ware. We install concealed flush mechanisms, rainfall thermostatic showers, glass enclosures, and modern sensor taps.",
    categoryId: 3,
    subcategoryId: 5,
    imageUrl: "https://images.pexels.com/photos/1910472/pexels-photo-1910472.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Geberit / Grohe concealed cistern mounting", "Tempered glass shower cubicle installation", "Water heater installation & pressure test", "Precision silicone sealing & zero leaks"]),
    estimatedPriceRange: "Per Bathroom / Negotiable",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 12,
  },

  // ─── CATEGORY 4: PROPERTY & INTERIORS (4 Services - All Negotiable) ───
  {
    id: 13,
    name: "POP Ceiling Design, Cornices & Ambient Lighting",
    slug: "pop-ceiling-design",
    shortDescription: "Modern 3D false ceilings, custom cove LED strip troughs, recessed spotlights, and decorative cornices.",
    fullDescription: "Custom POP ceiling installations tailored to your architectural layout. We design recessed ambient lighting channels, floating ceiling islands, decorative moldings, and seamless joint finishes.",
    categoryId: 4,
    subcategoryId: 7,
    imageUrl: "https://images.pexels.com/photos/8961438/pexels-photo-8961438.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Precision laser leveling alignment", "Moisture-resistant high-grade plaster", "Concealed ambient LED lighting troughs", "Fast clean room installation"]),
    estimatedPriceRange: "Custom Design (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 13,
  },
  {
    id: 14,
    name: "Complete Building Painting & Wall Screeding",
    slug: "building-painting",
    shortDescription: "Interior and exterior premium painting, smooth wall screeding, stucco marble, and textured finishes.",
    fullDescription: "Professional surface preparation, sanding, crack filling, wall screeding, and multi-coat application using weatherproof premium emulsion, satin, and gloss paints.",
    categoryId: 4,
    subcategoryId: 8,
    imageUrl: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Dustless surface sanding & skim coating", "Anti-fungal, washable premium paints", "Stucco marble & accent feature walls", "Clean-up & zero paint splatter guarantee"]),
    estimatedPriceRange: "Custom Scope (Negotiable)",
    pricingType: "quote",
    featured: true,
    active: true,
    sortOrder: 14,
  },
  {
    id: 15,
    name: "Stone-Coated Roof Installation & Structural Truss",
    slug: "stone-coated-roof-truss",
    shortDescription: "Gerard stone-coated roofing tiles, aluminium long-span sheets, treated timber/steel truss, and guttering.",
    fullDescription: "End-to-end roofing engineering. We construct engineered wood or steel roof trusses, install premium stone-coated shingles, flashing, fascia boards, and rainwater harvesting gutters.",
    categoryId: 4,
    subcategoryId: 7,
    imageUrl: "https://images.pexels.com/photos/5997994/pexels-photo-5997994.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Original 50-year warranty stone-coated tiles", "Treated anti-termite hardwood truss", "Leak-proof valley gutter and ridge caps", "Wind-resistant cyclone nailing system"]),
    estimatedPriceRange: "Custom Roof Area (Negotiable)",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 15,
  },
  {
    id: 16,
    name: "Ceramic, Porcelain & Granite Floor Tiling",
    slug: "ceramic-porcelain-granite-tiling",
    shortDescription: "Laser-leveled floor and wall tiling, high-gloss porcelain, non-slip bathroom tiles, and granite staircases.",
    fullDescription: "High-precision tiling for living rooms, kitchens, bathrooms, and commercial halls. Includes laser leveling, high-strength adhesive bedding, tile spacers, and waterproof epoxy grouting.",
    categoryId: 4,
    subcategoryId: 8,
    imageUrl: "https://images.pexels.com/photos/6474471/pexels-photo-6474471.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: null,
    price: null, // Negotiable
    features: JSON.stringify(["Laser precision alignment & leveling", "Crack-resistant polymer tile adhesive", "Waterproof anti-stain epoxy grout", "Granite threshold & staircase cladding"]),
    estimatedPriceRange: "Per Square Meter / Negotiable",
    pricingType: "quote",
    featured: false,
    active: true,
    sortOrder: 16,
  },
];

export const mockSubcategories: Subcategory[] = [
  { id: 1, categoryId: 1, name: "Building & Civil Construction", slug: "building-civil", description: "Residential, commercial, and structural civil works", icon: "building", imageUrl: null, sortOrder: 1, active: true },
  { id: 2, categoryId: 1, name: "Renovation & Remodeling", slug: "renovation", description: "Structural repairs, extensions, and modern upgrades", icon: "wrench", imageUrl: null, sortOrder: 2, active: true },
  { id: 3, categoryId: 2, name: "Building Electrical Wiring", slug: "electrical-wiring", description: "Conduit wiring, distribution boards, and fittings", icon: "zap", imageUrl: null, sortOrder: 1, active: true },
  { id: 4, categoryId: 2, name: "Solar & Smart Systems", slug: "solar-systems", description: "Off-grid, hybrid solar power generation setups", icon: "zap", imageUrl: null, sortOrder: 2, active: true },
  { id: 5, categoryId: 3, name: "Piping & Drainage", slug: "piping-drainage", description: "PEX/PPR water supply and waste drainage lines", icon: "droplets", imageUrl: null, sortOrder: 1, active: true },
  { id: 6, categoryId: 3, name: "Borehole & Water Treatment", slug: "borehole-water", description: "Well drilling, pumps, and water purification", icon: "droplets", imageUrl: null, sortOrder: 2, active: true },
  { id: 7, categoryId: 4, name: "Roofing & POP Ceiling", slug: "roofing-ceiling", description: "Stone-coated tiles, aluminium, and POP ceilings", icon: "home", imageUrl: null, sortOrder: 1, active: true },
  { id: 8, categoryId: 4, name: "Painting, Screeding & Tiling", slug: "painting-finishes", description: "Wall screeding, textured paint, and porcelain tiling", icon: "home", imageUrl: null, sortOrder: 2, active: true },
];

export const mockUsers: User[] = [
  {
    id: 1,
    role: "admin",
    fullName: "QuestMore Administrator",
    email: "questdmore@gmail.com",
    phone: "+2348156307091",
    avatarUrl: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=300&w=300",
    verificationStatus: "verified",
    verified: true,
  },
];

export const mockRequests: ServiceRequest[] = [];

export const mockReviews: Review[] = [];

export const mockGalleryItems: ProjectGalleryItem[] = [
  {
    id: 1,
    serviceId: 1,
    categoryId: 1,
    title: "5-Bedroom Duplex Renovation",
    description: "Full exterior remodeling, POP ceiling installation, and modern solar lighting setup.",
    beforeImageUrl: "https://images.pexels.com/photos/8961438/pexels-photo-8961438.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    afterImageUrl: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    location: "Lokogama, Abuja",
    featured: true,
  },
  {
    id: 2,
    serviceId: 2,
    categoryId: 2,
    title: "15kVA Commercial Solar Power System",
    description: "Installation of 24 Mono PERC solar panels with 30kWh Lithium storage bank.",
    beforeImageUrl: "https://images.pexels.com/photos/27928762/pexels-photo-27928762.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    afterImageUrl: "https://images.pexels.com/photos/9875441/pexels-photo-9875441.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    location: "Wuse 2, Abuja",
    featured: true,
  },
];

export const mockFaqs: FAQ[] = [
  { id: 1, categoryId: 1, question: "How does QuestMore verify engineers and contractors?", answer: "All professionals undergo identity verification, certification checks, physical workplace inspections, and past project reviews before being approved for jobs.", sortOrder: 1, active: true },
  { id: 2, categoryId: 2, question: "What is the ₦5,000 Booking Fee for?", answer: "The ₦5,000 Booking Fee covers job scoping, engineer dispatch verification, and unlocks direct secure communication between you and verified QuestMore engineering specialists. It is charged once per cart/request.", sortOrder: 2, active: true },
  { id: 3, categoryId: 3, question: "How does pricing work for Negotiable services?", answer: "For services without a fixed price, you only pay the ₦5,000 booking fee initially. Once payment is verified, an engineering supervisor contacts you to review scope, inspect site requirements, and agree on the final project cost.", sortOrder: 3, active: true },
  { id: 4, categoryId: 4, question: "Is there a warranty on completed engineering services?", answer: "Yes! All structural, solar, and installation services carry a QuestMore Quality Assurance Warranty ranging from 6 months to 5 years depending on service type.", sortOrder: 4, active: true },
];

export const mockAreas: ServiceArea[] = [
  { id: 1, name: "Maitama", state: "Abuja (FCT)", active: true },
  { id: 2, name: "Asokoro", state: "Abuja (FCT)", active: true },
  { id: 3, name: "Gwarinpa", state: "Abuja (FCT)", active: true },
  { id: 4, name: "Wuse 2", state: "Abuja (FCT)", active: true },
  { id: 5, name: "Ikeja", state: "Lagos", active: true },
  { id: 6, name: "Lekki Phase 1", state: "Lagos", active: true },
  { id: 7, name: "Port Harcourt City", state: "Rivers", active: true },
];
